build:
  stage: build
  tags:
    - docker
    - amd64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker tag $CI_REGISTRY_IMAGE:latest timroemisch/mqtt-s7-connector:latest
    - docker push timroemisch/mqtt-s7-connector:latest
  only:
    - master

build-rpi:
  stage: build
  tags:
    - docker
    - rpi
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:rpi .
    - docker push $CI_REGISTRY_IMAGE:rpi

    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker tag $CI_REGISTRY_IMAGE:rpi timroemisch/mqtt-s7-connector:rpi
    - docker push timroemisch/mqtt-s7-connector:rpi
  only:
    - master

dev-build:
  stage: build
  tags:
    - docker
    - amd64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG
  except:
    - master
